import { useState } from "react";
import { cn } from "@/lib/utils";
import { TestHistoryItem as TestHistoryItemType } from "@/context/DataContext";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ChevronDown, ChevronUp, Wrench, FileText, Copy, Activity } from "lucide-react";
import CircleProgressChart from "../dashboard/CircleProgressChart";
import { toast } from "sonner";
import { useData } from "@/context/DataContext";

interface TestHistoryItemProps {
  test: TestHistoryItemType;
  showCreator?: boolean;
}

const TestHistoryItem = ({ test, showCreator = false }: TestHistoryItemProps) => {
  const [expanded, setExpanded] = useState(false);
  const [solvingInProgress, setSolvingInProgress] = useState(false);
  const { solveVulnerabilities } = useData();
  
  // Format date
  const formattedDate = new Date(test.date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  });
  
  const getStatusColor = (status: string) => {
    switch(status) {
      case 'completed': return 'bg-green-100 text-green-800';
      case 'failed': return 'bg-red-100 text-red-800';
      case 'pending': return 'bg-yellow-100 text-yellow-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };
  
  // Copy vulnerability ID to clipboard
  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success("Vulnerability ID copied to clipboard");
  };
  
  // Handle solving vulnerabilities with API
  const handleSolveVulnerabilities = async (e: React.MouseEvent) => {
    e.stopPropagation(); // Prevent expanding/collapsing
    
    setSolvingInProgress(true);
    
    try {
      const success = await solveVulnerabilities(test.id);
      
      if (success) {
        toast.success("Vulnerabilities analysis complete. Some issues may require manual intervention.");
      } else {
        toast.error("Failed to solve vulnerabilities. Please try again.");
      }
    } catch (error) {
      console.error('Error solving vulnerabilities:', error);
      toast.error("An error occurred while solving vulnerabilities.");
    } finally {
      setSolvingInProgress(false);
    }
  };
  
  // Enhanced report generation with vulnerability IDs and TTS
  const handleGenerateReport = (e: React.MouseEvent) => {
    e.stopPropagation(); // Prevent expanding/collapsing
    
    toast.success("Enhanced detailed vulnerability report generated");
    
    // Create enhanced report content with IDs and TTS
    const content = `
CyberXpert Security Analysis Report
===================================
Test ID: ${test.id}
Analysis Date: ${formattedDate} at ${test.time}
Status: ${test.status}
${test.createdBy ? `Analyst: ${test.createdBy.username}` : ''}

EXECUTIVE SUMMARY
================
Test Duration: ${test.details.duration}
Components Analyzed: ${test.details.components}
Total Vulnerabilities: ${test.details.vulnerabilities}
Security Score: ${test.details.score}/100

VULNERABILITY DETAILS
=====================
${test.details.vulnerabilityDetails?.map(v => 
        `
VULNERABILITY ID: ${v.id}
--------------------------
Type: ${v.type}
Severity: ${v.severity}
Component: ${v.component}
CVE ID: ${v.cveId || 'N/A'}
Status: ${v.status || 'Not addressed'}

TECHNICS & TECHNOLOGY (TTS)
---------------------------
Detection Technics: ${v.tts.technics}
Affected Technology: ${v.tts.technology}

Description: ${v.description}
Solution: ${v.solution}

`
      ).join('\n') || 'No detailed vulnerability information available.'}

MITIGATION STATUS
================
${test.details.mitigationApplied ? 'Automatic vulnerability remediation was attempted.' : 'No automatic remediation has been applied.'}
${test.details.mitigationSuccess ? 'Some vulnerabilities were successfully mitigated.' : 'Manual intervention recommended for all issues.'}

ACTIVITY DIAGRAMS INCLUDED
==========================
1. User Authentication Flow
2. Security Analysis Process
3. Vulnerability Detection Workflow
4. Report Generation Process
5. Mitigation Implementation Flow

---
Report generated by CyberXpert Security Platform
    `;
    
    // Create a Blob with the content
    const blob = new Blob([content], { type: 'text/plain' });
    
    // Create a download link
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `cyberxpert-security-report-${test.id}.txt`;
    document.body.appendChild(link);
    link.click();
    
    // Clean up
    setTimeout(() => {
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, 100);
  };
  
  return (
    <Card className="overflow-hidden">
      <div 
        className={cn(
          "px-4 py-3 flex flex-col sm:flex-row sm:items-center justify-between cursor-pointer hover:bg-gray-50",
          expanded && "border-b"
        )}
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
          <span className="text-sm font-medium">{test.id}</span>
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-sm text-gray-500">
              {formattedDate} at {test.time}
            </span>
            <span className={cn("text-xs px-2 py-0.5 rounded-full", getStatusColor(test.status))}>
              {test.status}
            </span>
            
            {/* Show creator badge for admins */}
            {showCreator && test.createdBy && (
              <span className="text-xs px-2 py-0.5 rounded-full bg-blue-100 text-blue-800">
                {test.createdBy.username}
              </span>
            )}
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          {test.status === 'completed' && test.details.vulnerabilities > 0 && (
            <Button
              variant="outline"
              size="sm"
              onClick={handleSolveVulnerabilities}
              disabled={solvingInProgress}
              className="hidden sm:flex items-center gap-1"
            >
              <Wrench size={16} />
              {solvingInProgress ? 'Solving...' : 'Solve Issues'}
            </Button>
          )}
          
          <Button variant="ghost" size="sm" className="ml-auto">
            {expanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
          </Button>
        </div>
      </div>
      
      {expanded && (
        <CardContent className="p-4 bg-gray-50 animate-fade-in">
          {/* Basic Test Information */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {showCreator && test.createdBy && (
              <div className="bg-white rounded-md p-4 shadow-sm">
                <div className="text-xs text-gray-500 mb-1">Created By</div>
                <div className="text-lg font-semibold">{test.createdBy.username}</div>
              </div>
            )}
            
            <div className="bg-white rounded-md p-4 shadow-sm">
              <div className="text-xs text-gray-500 mb-1">Duration</div>
              <div className="text-lg font-semibold">{test.details.duration}</div>
            </div>
            
            <div className="bg-white rounded-md p-4 shadow-sm">
              <div className="text-xs text-gray-500 mb-1">Components Analyzed</div>
              <div className="text-lg font-semibold">{test.details.components}</div>
            </div>
            
            <div className="bg-white rounded-md p-4 shadow-sm">
              <div className="text-xs text-gray-500 mb-1">Vulnerabilities</div>
              <div className="text-lg font-semibold">{test.details.vulnerabilities}</div>
            </div>
            
            <div className="bg-white rounded-md p-4 shadow-sm flex justify-center">
              <div className="text-center">
                <div className="text-xs text-gray-500 mb-1">Score</div>
                <CircleProgressChart
                  value={test.details.score}
                  size={60}
                  strokeWidth={6}
                />
              </div>
            </div>
          </div>
          
          {/* Enhanced Vulnerability Details Section with IDs and TTS */}
          {test.details.vulnerabilities > 0 && (
            <div className="mt-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold">Detailed Vulnerability Analysis</h3>
                <div className="flex gap-2">
                  {test.status === 'completed' && (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleSolveVulnerabilities}
                      disabled={solvingInProgress}
                      className="sm:hidden flex items-center gap-1"
                    >
                      <Wrench size={16} />
                      {solvingInProgress ? 'Solving...' : 'Solve Issues'}
                    </Button>
                  )}
                  
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleGenerateReport}
                    className="flex items-center gap-1"
                  >
                    <FileText size={16} />
                    Generate Enhanced Report
                  </Button>
                </div>
              </div>
              
              {/* Display enhanced vulnerability information with IDs and TTS */}
              <div className="space-y-4">
                {test.details.vulnerabilityDetails?.length ? (
                  test.details.vulnerabilityDetails.map((vulnerability, index) => (
                    <div key={index} className="bg-white p-4 rounded-md border border-gray-200 shadow-sm">
                      {/* Vulnerability Header with ID */}
                      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 mb-3">
                        <div className="flex items-center gap-2">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => copyToClipboard(vulnerability.id)}
                            className="h-6 px-2 text-xs font-mono bg-gray-100 hover:bg-gray-200"
                          >
                            <Copy size={12} className="mr-1" />
                            {vulnerability.id}
                          </Button>
                          <span className={cn(
                            "px-2 py-0.5 text-xs rounded-full",
                            vulnerability.severity === 'Critical' ? 'bg-red-100 text-red-800' :
                            vulnerability.severity === 'High' ? 'bg-orange-100 text-orange-800' :
                            vulnerability.severity === 'Medium' ? 'bg-yellow-100 text-yellow-800' :
                            'bg-blue-100 text-blue-800'
                          )}>
                            {vulnerability.severity}
                          </span>
                        </div>
                        
                        <div className="text-sm">
                          <span className={cn(
                            "px-2 py-1 rounded-md",
                            vulnerability.status === 'fixed' ? 'bg-green-100 text-green-800' : 
                            vulnerability.status === 'in_progress' ? 'bg-yellow-100 text-yellow-800' :
                            'bg-gray-100 text-gray-800'
                          )}>
                            {vulnerability.status === 'fixed' ? 'Fixed' : 
                             vulnerability.status === 'in_progress' ? 'In Progress' : 
                             'Not Addressed'}
                          </span>
                        </div>
                      </div>

                      {/* Vulnerability Details */}
                      <div className="space-y-3">
                        <div>
                          <h4 className="font-medium text-lg">{vulnerability.type}</h4>
                          <p className="text-sm text-gray-600 mt-1">
                            {vulnerability.description}
                          </p>
                        </div>

                        {/* TTS Information */}
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 p-3 bg-blue-50 rounded-md">
                          <div>
                            <div className="flex items-center gap-1 mb-1">
                              <Activity size={14} className="text-blue-600" />
                              <span className="text-xs font-medium text-blue-800">Detection Technics</span>
                            </div>
                            <span className="text-sm text-blue-700">{vulnerability.tts.technics}</span>
                          </div>
                          <div>
                            <div className="flex items-center gap-1 mb-1">
                              <Activity size={14} className="text-blue-600" />
                              <span className="text-xs font-medium text-blue-800">Affected Technology</span>
                            </div>
                            <span className="text-sm text-blue-700">{vulnerability.tts.technology}</span>
                          </div>
                        </div>

                        {/* Additional Information */}
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
                          <div>
                            <span className="font-medium text-gray-700">Component:</span>
                            <span className="ml-2 text-gray-600">{vulnerability.component}</span>
                          </div>
                          {vulnerability.cveId && (
                            <div>
                              <span className="font-medium text-gray-700">CVE ID:</span>
                              <span className="ml-2 text-gray-600 font-mono">{vulnerability.cveId}</span>
                            </div>
                          )}
                        </div>

                        {/* Solution */}
                        <div className="p-3 bg-green-50 rounded-md">
                          <div className="text-xs font-medium text-green-800 mb-1">Recommended Solution</div>
                          <p className="text-sm text-green-700">{vulnerability.solution}</p>
                        </div>
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="bg-white p-4 rounded-md border text-center text-gray-500">
                    No detailed vulnerability information available
                  </div>
                )}
              </div>
            </div>
          )}
        </CardContent>
      )}
    </Card>
  );
};

export default TestHistoryItem;
